-- Add all new category values to the location_category enum
-- Note: PostgreSQL allows adding new values to enums

ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Record Labels';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Music Venues';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Festivals & Live Event Organisers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Artist Management Agencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Booking Agencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Music Publishers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Recording Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Rehearsal Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Post-Production Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Production Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Independent Artists & Bands';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'DJs & Electronic Producers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Audio Engineers & Mix/Mastering Services';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Music Technology Startups';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Technology Labs';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Digital Media Agencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Web3 / Blockchain Creative Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Film & TV Production Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Art Galleries';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Artist-Run Initiatives';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Cultural Centres';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Hubs & Coworking Spaces';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Community Arts Organisations';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Theatre Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Dance Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Design Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Animation & Motion Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Game Development Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'XR/AR/VR Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Immersive Media Creators';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Content Creators & Creative Influencers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Photography Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Videography Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Event Production & Technical Services';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Lighting, Sound & Staging Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Event Ticketing Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Publicists & PR Agencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Marketing & Creative Communications Agencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Cultural Festivals';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Education & Training Providers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Talent Development Programs & Residencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Marketplaces & Digital Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Tools & Software Providers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Podcast Studios & Networks';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Cultural Research & Policy Organisations';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Artist Services & Freelance Creative Providers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Community Radio Stations';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Music Retailers & Instrument Stores';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Arts Foundations & Funders';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Music Distributors';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Sync Licensing Agencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Music Supervisors';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Composer Services';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Audio Sample Library Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Music Data & Analytics Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Music Education Platforms & Tutors';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Instrument Makers & Luthiers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Audio Hardware Manufacturers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Micro-labels';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Artist Collectives & Creative Co-ops';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Streetwear & Creative Fashion Brands';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Fabrication Workshops';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Makerspaces & Fab Labs';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Cultural Heritage Organisations';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Museums & Exhibition Spaces';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Public Art Producers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Festival Infrastructure Suppliers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Backline Hire Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Touring & Logistics Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Set Designers & Scenic Fabricators';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Prop & Costume Workshops';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Industrial Designers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Sound Art & Experimental Media Groups';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Lighting Designers & Visual Effects Artists';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Projection Mapping Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Generative Art Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'AI Creative Production Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'AI Music Generation Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Live Streaming Production Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Hybrid Events & Virtual Venue Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Content Syndication Networks';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Print Shops';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Zine Publishers & Micro-presses';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Art Supply Retailers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Craft & Artisan Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Retreats & Residency Spaces';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Interdisciplinary Art–Tech Labs';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Civic & Urban Creative Placemaking Organisations';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Regional Creative Networks';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Cultural Tourism Operators';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Indigenous Art Centres';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Dance Schools & Academies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Storytelling & Narrative Design Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Workshops & Education Providers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Professional Guilds & Industry Associations';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Funding Consultants';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Cultural Strategy Consultancies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Incubators & Accelerators';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Social Enterprises';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Independent Media Outlets';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Community Makers Markets';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Fashion & Textile Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Illustrators & Concept Artists';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Model & Talent Casting Agencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Voiceover Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Location Scouts & Production Support';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'NFT Art Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Metaverse Experience Builders';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Digital Collectible Creators';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Online Creative Marketplaces';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Crowdfunding Platforms for Creators';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Coworking/Hotdesk Spaces';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Wearable Tech Creators';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Immersive Theatre Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Open Studios & Artist Exchanges';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Venue Discovery Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Artist Portfolio Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Music Monetisation Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Data & Metadata Services';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Archival & Digitisation Services';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Cultural Mapping Organisations';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Public Music Programs & Youth Music Foundations';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Software Development Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Full-Stack Development Agencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Frontend/Backend Developers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'App Development Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Web Development Agencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Custom Platform Builders';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'SaaS Creators';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Technology Agencies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'AI Research & Development Labs';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'AI-Driven Creative Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'AI Video/Audio Generation Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Machine Learning Engineers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Data Science & Analytics Firms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Data Engineering Services';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Digital Signal Processing Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Audio AI Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Music Recommendation Engines';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Audio Plugin Developers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'DAW Developers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Tools & Productivity Software Makers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Immersive Technology Labs';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS '3D Modelling & Simulation Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Virtual Production Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Realtime Engine Specialists';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Game Audio & Interactive Sound Designers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Interactive Media Designers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Smart Contract Developers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Motion Capture Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Robotics Labs';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'IoT & Wearable Tech Designers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Haptics & Sensory Experience Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Streaming Technology Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Cloud Media Infrastructure Providers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Cybersecurity for Creative Industries';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'DevOps & Cloud Engineering Services';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'API Providers & Developer Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Audio Infrastructure Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Video Encoding & Live-stream Tech';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Automation Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'DRM & Rights Management Services';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Asset Management & Metadata Software';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Digital Preservation Technology';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'E-commerce Platforms for Creators';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Multi-vendor Marketplace Platforms';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'White-label Ticketing Providers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Event Technology & RFID/NFC Systems';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Spatial Audio Technology Companies';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Embedded Systems for Art & Music';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS '3D Printing & Fabrication Tech Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Digital Fabrication Labs';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Creative Coding Studios';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Interactive Installation Technologists';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Projection Mapping Tech Providers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Lighting Control System Developers';
ALTER TYPE location_category ADD VALUE IF NOT EXISTS 'Show Control & Live Event Software';